"""Session alias generation with 1:1 Slack emoji mapping.

Replaces ``coolname`` with a custom generator.  Every noun AND adjective
has an exact standard Slack emoji shortcode — no approximations, no custom
emoji needed.  Aliases are ``adjective-noun`` pairs (e.g. ``blazing-rocket``)
and produce *two* emoji reactions on the thread root.

~120 adjectives × ~150 nouns ≈ 18,000 unique combinations.
"""

from __future__ import annotations

import random

# ---------------------------------------------------------------------------
# Nouns — every entry maps to an *exact* standard Slack emoji shortcode.
# Sourced from the iamcal/emoji-data set used by Slack.
# ---------------------------------------------------------------------------

NOUNS: dict[str, str] = {
    # -- Animals --
    "ant": "ant",
    "badger": "badger",
    "bat": "bat",
    "bear": "bear",
    "beaver": "beaver",
    "bee": "honeybee",
    "beetle": "beetle",
    "bird": "bird",
    "bison": "bison",
    "boar": "boar",
    "bug": "bug",
    "butterfly": "butterfly",
    "camel": "camel",
    "cat": "cat",
    "chicken": "chicken",
    "chipmunk": "chipmunk",
    "cow": "cow",
    "crab": "crab",
    "cricket": "cricket",
    "crocodile": "crocodile",
    "deer": "deer",
    "dodo": "dodo",
    "dog": "dog",
    "dolphin": "dolphin",
    "donkey": "donkey",
    "dove": "dove",
    "dragon": "dragon",
    "duck": "duck",
    "eagle": "eagle",
    "elephant": "elephant",
    "flamingo": "flamingo",
    "fox": "fox_face",
    "frog": "frog",
    "giraffe": "giraffe_face",
    "goat": "goat",
    "goose": "goose",
    "gorilla": "gorilla",
    "hedgehog": "hedgehog",
    "hippo": "hippopotamus",
    "horse": "horse",
    "kangaroo": "kangaroo",
    "koala": "koala",
    "leopard": "leopard",
    "lion": "lion_face",
    "lizard": "lizard",
    "llama": "llama",
    "lobster": "lobster",
    "mammoth": "mammoth",
    "monkey": "monkey",
    "moose": "moose",
    "mosquito": "mosquito",
    "mouse": "mouse",
    "octopus": "octopus",
    "orangutan": "orangutan",
    "otter": "otter",
    "owl": "owl",
    "ox": "ox",
    "panda": "panda_face",
    "parrot": "parrot",
    "peacock": "peacock",
    "penguin": "penguin",
    "pig": "pig",
    "poodle": "poodle",
    "rabbit": "rabbit",
    "raccoon": "raccoon",
    "ram": "ram",
    "rat": "rat",
    "rhino": "rhinoceros",
    "rooster": "rooster",
    "scorpion": "scorpion",
    "seal": "seal",
    "shark": "shark",
    "shrimp": "shrimp",
    "skunk": "skunk",
    "sloth": "sloth",
    "snail": "snail",
    "snake": "snake",
    "spider": "spider",
    "squid": "squid",
    "swan": "swan",
    "tiger": "tiger",
    "turkey": "turkey",
    "turtle": "turtle",
    "unicorn": "unicorn_face",
    "whale": "whale",
    "wolf": "wolf",
    "worm": "worm",
    "zebra": "zebra_face",
    # -- Food & drink --
    "avocado": "avocado",
    "banana": "banana",
    "broccoli": "broccoli",
    "burrito": "burrito",
    "cake": "cake",
    "candy": "candy",
    "cherry": "cherries",
    "chestnut": "chestnut",
    "coconut": "coconut",
    "cookie": "cookie",
    "corn": "corn",
    "cupcake": "cupcake",
    "doughnut": "doughnut",
    "grapes": "grapes",
    "hamburger": "hamburger",
    "lemon": "lemon",
    "mango": "mango",
    "melon": "melon",
    "mushroom": "mushroom",
    "peach": "peach",
    "peanut": "peanuts",
    "pear": "pear",
    "pepper": "hot_pepper",
    "pie": "pie",
    "pineapple": "pineapple",
    "pizza": "pizza",
    "potato": "potato",
    "pretzel": "pretzel",
    "strawberry": "strawberry",
    "taco": "taco",
    "tomato": "tomato",
    "waffle": "waffle",
    "watermelon": "watermelon",
    # -- Nature & weather --
    "cactus": "cactus",
    "comet": "comet",
    "crystal": "crystal_ball",
    "cyclone": "cyclone",
    "flame": "fire",
    "globe": "earth_americas",
    "leaf": "fallen_leaf",
    "moon": "full_moon",
    "mountain": "mountain",
    "ocean": "ocean",
    "rainbow": "rainbow",
    "snowflake": "snowflake",
    "star": "star",
    "sunflower": "sunflower",
    "tornado": "tornado",
    "tulip": "tulip",
    "volcano": "volcano",
    "wave": "ocean",
    # -- Objects & things --
    "anchor": "anchor",
    "balloon": "balloon",
    "bell": "bell",
    "bomb": "bomb",
    "bone": "bone",
    "book": "book",
    "boot": "boot",
    "boomerang": "boomerang",
    "brick": "bricks",
    "broom": "broom",
    "bucket": "bucket",
    "candle": "candle",
    "compass": "compass",
    "crown": "crown",
    "diamond": "gem",
    "drum": "drum_with_drumsticks",
    "feather": "feather",
    "flashlight": "flashlight",
    "gear": "gear",
    "guitar": "guitar",
    "hammer": "hammer",
    "hook": "hook",
    "key": "key",
    "kite": "kite",
    "knot": "knot",
    "ladder": "ladder",
    "lantern": "izakaya_lantern",
    "magnet": "magnet",
    "mirror": "mirror",
    "parachute": "parachute",
    "puzzle": "jigsaw",
    "ribbon": "ribbon",
    "rocket": "rocket",
    "satellite": "satellite",
    "scroll": "scroll",
    "shield": "shield",
    "sponge": "sponge",
    "telescope": "telescope",
    "tent": "tent",
    "thread": "thread",
    "trophy": "trophy",
    "wheel": "wheel",
    "wrench": "wrench",
    "yarn": "yarn",
    # -- Vehicles & transport --
    "canoe": "canoe",
    "helicopter": "helicopter",
    "sailboat": "sailboat",
    "sled": "sled",
}

# ---------------------------------------------------------------------------
# Adjectives — each maps to a standard Slack emoji shortcode.
# ---------------------------------------------------------------------------

ADJECTIVES: dict[str, str] = {
    # -- Temperature & weather --
    "arctic": "snowflake",
    "blazing": "fire",
    "breezy": "wind_blowing_face",
    "foggy": "fog",
    "frozen": "ice_cube",
    "frosty": "snowman",
    "gusty": "dash",
    "icy": "cold_face",
    "misty": "fog",
    "molten": "volcano",
    "snowy": "cloud",
    "solar": "sunny",
    "stormy": "thunder_cloud_and_rain",
    "sunny": "sun_with_face",
    "tidal": "ocean",
    "warm": "hotsprings",
    "windy": "leaves",
    "wintry": "snowflake",
    # -- Light & color --
    "amber": "large_orange_circle",
    "bright": "high_brightness",
    "cobalt": "large_blue_circle",
    "coral": "coral",
    "crimson": "red_circle",
    "cyan": "large_blue_circle",
    "dark": "new_moon",
    "emerald": "large_green_circle",
    "golden": "star2",
    "jade": "large_green_circle",
    "lavender": "large_purple_circle",
    "neon": "zap",
    "onyx": "black_circle",
    "pale": "white_circle",
    "rosy": "cherry_blossom",
    "ruby": "red_circle",
    "scarlet": "red_circle",
    "silver": "white_circle",
    "topaz": "large_yellow_circle",
    "vivid": "rainbow",
    # -- Material & texture --
    "bronze": "coin",
    "carbon": "black_large_square",
    "chrome": "mirror",
    "copper": "coin",
    "flint": "rock",
    "gilded": "crown",
    "granite": "rock",
    "iron": "chains",
    "ivory": "bone",
    "marble": "moyai",
    "mossy": "herb",
    "opal": "gem",
    "paper": "scroll",
    "pearly": "shell",
    "plaid": "shirt",
    "rustic": "wood",
    "sandy": "beach_with_umbrella",
    "steel": "shield",
    "stony": "rock",
    "timber": "wood",
    "velvet": "ribbon",
    # -- Sound & motion --
    "acoustic": "guitar",
    "echo": "loud_sound",
    "hushed": "shushing_face",
    "muted": "mute",
    "quiet": "shushing_face",
    "rapid": "fast_forward",
    "silent": "zipper_mouth_face",
    "sonic": "boom",
    "swift": "dash",
    "turbo": "rocket",
    "zippy": "racing_car",
    # -- Space & cosmic --
    "astral": "milky_way",
    "cosmic": "ringed_planet",
    "galactic": "stars",
    "lunar": "crescent_moon",
    "nebula": "milky_way",
    "orbit": "ringed_planet",
    "stellar": "star2",
    # -- Mood & character --
    "bold": "muscle",
    "brave": "crossed_swords",
    "calm": "dove_of_peace",
    "clever": "brain",
    "cunning": "fox_face",
    "daring": "dart",
    "deft": "pinching_hand",
    "eager": "eyes",
    "epic": "trophy",
    "feral": "wolf",
    "fierce": "fire",
    "gentle": "dove_of_peace",
    "humble": "pray",
    "keen": "mag",
    "lavish": "money_with_wings",
    "lofty": "mountain",
    "lucky": "four_leaf_clover",
    "mighty": "muscle",
    "mystic": "crystal_ball",
    "nimble": "wind_blowing_face",
    "noble": "crown",
    "proud": "lion_face",
    "regal": "crown",
    "rugged": "mountain",
    "sage": "herb",
    "sharp": "hocho",
    "spicy": "hot_pepper",
    "steady": "anchor",
    "subtle": "mag",
    "wild": "boom",
    "zen": "pray",
    # -- Other evocative --
    "alpine": "mountain",
    "ancient": "moyai",
    "atomic": "atom_symbol",
    "dusty": "wind_blowing_face",
    "electric": "zap",
    "ember": "fire",
    "fossil": "bone",
    "glacial": "snowflake",
    "hidden": "detective",
    "hollow": "hole",
    "idle": "zzz",
    "kindled": "candle",
    "laser": "flashlight",
    "lean": "dart",
    "lone": "cactus",
    "nomad": "compass",
    "obsidian": "black_large_square",
    "pastel": "art",
    "polar": "polar_bear",
    "prism": "rainbow",
    "shadow": "new_moon",
    "smoky": "fog",
    "twilight": "city_sunset",
    "vast": "earth_americas",
    "wired": "electric_plug",
    "wispy": "cloud",
}


def generate_alias() -> str:
    """Generate a session alias like ``blazing-rocket``.

    Returns an ``adjective-noun`` string.  Both parts map 1:1 to
    standard Slack emoji via :data:`ADJECTIVES` and :data:`NOUNS`.

    ~120 × ~150 ≈ 18,000 unique combinations.
    """
    adj = random.choice(tuple(ADJECTIVES.keys()))
    noun = random.choice(tuple(NOUNS.keys()))
    return f"{adj}-{noun}"


def emojis_for_alias(alias: str) -> tuple[str, str]:
    """Return (adjective_emoji, noun_emoji) for a session alias.

    Both are standard Slack emoji shortcodes (without colons).
    Falls back to ``sparkles`` for unrecognised parts.
    """
    parts = alias.split("-", 1)
    if len(parts) == 2:
        adj, noun = parts
    else:
        adj, noun = "", parts[0]
    return (
        ADJECTIVES.get(adj, "sparkles"),
        NOUNS.get(noun, "sparkles"),
    )


# Keep a single-emoji convenience function for backward compatibility.
def emoji_for_alias(alias: str) -> str:
    """Return the noun emoji for a session alias (legacy single-emoji API)."""
    _, noun_emoji = emojis_for_alias(alias)
    return noun_emoji
